### ISSUE TITLE
How to correctly solve dependencies zlib, ssh2, ssl, curl

### ISSUE THREAD

**Issue by IOTeule** [noelmartinon/mboxzilla#2]
Having trouble to build this.
Could you give some hint, how to solve the installation of deps and is there any reason why there is no deps folder directly in this repro ?

E.g. curl:
1) Error
mboxzilla.hpp:40:10: fatal error: curl/curl.h: Datei oder Verzeichnis nicht gefunden
   40 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~
2) sudo apt install curl
3) curl (IS WORKING)
curl: try 'curl --help' or 'curl --manual' for more information
4) Error still exists
mboxzilla.hpp:40:10: fatal error: curl/curl.h: Datei oder Verzeichnis nicht gefunden
   40 | #include <curl/curl.h>
      |          ^~~~~~~~~~~~~

Thx in advance

**Comment by noelmartinon** [comment]
Hello, try this : 
sudo apt install zlib1g-dev libcurl4-openssl-dev libssl-dev libssh2-1-dev
