### ISSUE TITLE
"From " line stripped, verbosity not working

### ISSUE THREAD

**Issue by ghost** [noelmartinon/mboxzilla#5]
I just want to start out by saying this is an awesome project, pretty much executes flawlessly. Using it to split my mbox files right now and it's working great.

Two things I noticed:

## From being stripped
The "From " line is getting stripped from the export. To keep the integrity of the originally export emails I think this line should be copied over to the file output. Some email clients provide hashes of an entire message's source and this would make the hashes mismatch.

This would only be an issue to some in a specific use case, but might be nice to implement as an option anyways

## Verbosity not initialized with logging library
- The verbosity option doesn't seem to be working, I've tried the exact format provided in the examples `-v 2` [from here](https://github.com/noelmartinon/mboxzilla/blob/master/README.md?plain=1#L148)  and `-v 3` for INFO level but there's no dice on the outputting of extra information

**Comment by noelmartinon** [comment]
Hello, thank you for your message. 
The "From " is used to separate the email in the inbox files. It's not an header of the eml format instead of "From:". So the integrity is maintained.
For the verbosity issue, it was under Windows ?
